pipes

diff --git a/pipelines/azp-pr.yml b/pipelines/azp-pr.yml
--- a/pipelines/azp-pr.yml
+++ b/pipelines/azp-pr.yml
@@ -1,137 +1,232 @@
+name: Pull request pipeline
+
+#
+# Setup pipeline triggers
+# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#triggers
+#
+
+# Enable Pull request validation triggers
+# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pr-trigger
 pr:
+  batch: true
   branches:
     include:
-      - master
+      - stg
+      - int
       - dev
+    exclude:
+      - pro
+      - master
   paths:
     exclude:
-      - pipelines/*
+    - README.md
+    - LICENSE.md
+    - docs/*
+    - helpers/*
+    - scripts/*
 
+# Disable Continuous integration (CI) for this pipeline
+# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#push-trigger
 trigger: none
 
+#
+# Setup pipeline environment
+#
+
+# Setup pipeline resources
+# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#resources
 resources:
   containers:
+  - container: gcloud
+    image:  google/cloud-sdk:243.0.0-slim
   - container: gitopsci
     image:  raelga/gitopsci:v1.0
 
+# Setup variable groups
+# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#variables
 variables:
-- group: DEMO
+- name: PROVIDER
+  value: gcp
+- name: ENVIRONMENT
+  value: $(System.PullRequest.TargetBranchName)
+- name: PREFIX
+  value: "PR$(System.PullRequest.PullRequestNumber)"
+- group: gcloud-environment
+  # The gcloud-environment contains:
+  #   - GCLOUD_SERVICE_ACCOUNT: The Google Cloud Service Account (as secret)
+  #   - GCLOUD_PROJECT_ID: The Google Cloud Project ID (as secret)
 
 stages:
 
-- stage: Infra
+- stage: Environment check
+  displayName: Check CI environment
   jobs:
-  - job: ProviderConfig
-    displayName: "Check Google Cloud SDK"
-    container: gitopsci
+
+  - job: GoogleCloudEnvCheck
+    displayName: Check Google Cloud environment"
+    container: gcloud
     steps:
 
-      - script: printenv
-
-      # - bash: |
-      #     # Create environment variable for correct distribution
-      #     export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
-
-      #     # Add the Cloud SDK distribution URI as a package source
-      #     echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
-
-      #     # Import the Google Cloud Platform public key
-      #     curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
-
-      #     # Update the package list and install the Cloud SDK
-      #     sudo apt-get update && sudo apt-get -y install google-cloud-sdk
-      # displayName: Install Google Cloud SDK
-
       - bash: |
-          which gcloud &> /dev/null \
-            || { echo "[!] gcloud SDK is not installed."; exit 1; } \
-            && echo "[i] gcloud installed with $(gcloud version | grep 'Google Cloud SDK')."
+          if which gcloud &> /dev/null;
+          then
+            echo "[i] gcloud installed with $(gcloud version | grep 'Google Cloud SDK').";
+          else
+            echo "[!] gcloud SDK is not installed."; exit 1;
+          fi
         displayName: Check Google Cloud SDK version
 
       - bash: |
-          test ! -z ${GCLOUD_SERVICE_ACCOUNT:-} \
-            || { echo "[!] GCLOUD_SERVICE_ACCOUNT environment variable must be set."; exit 1; } \
-            && {
-              gcloud auth activate-service-account \
-                --key-file <(echo ${GCLOUD_SERVICE_ACCOUNT} | base64 -d) \
-              || { echo "[!] Unable to activate the service account."; exit 1; } \
-              && echo  [i] "Service account set to $(gcloud config get-value account)."
-            }
-        displayName: Activate Google Cloud SDK service account
+          if test ! -z ${GCLOUD_SERVICE_ACCOUNT:-};
+          then
+            if gcloud auth activate-service-account \
+                --key-file <(echo ${GCLOUD_SERVICE_ACCOUNT} | base64 -d);
+            then
+              echo "[i] Service account $(gcloud config get-value account) set.";
+            else
+              echo "[!] Unable to activate the service account.";
+              exit 1;
+            fi
+          else
+            echo "[!] GCLOUD_SERVICE_ACCOUNT environment variable must be set.";
+            exit 1;
+          fi
+        displayName: Check Google Cloud SDK service account
         env:
           GCLOUD_SERVICE_ACCOUNT: $(GCLOUD_SERVICE_ACCOUNT)
 
       - bash: |
-          test ! -z ${GCLOUD_PROJECT_ID:-} \
-            || { echo "[!] GCLOUD_PROJECT_ID environment variable must be set."; exit 1; } \
-            && {
-              gcloud config set project ${GCLOUD_PROJECT_ID} \
-                || { echo "[!] Unable to set project ${GCLOUD_PROJECT_ID}."; exit 1; } \
-                && echo  [i] "gcloud project set to $(gcloud config get-value project).";
-            }
-        displayName: Activate Google Cloud SDK project
+          if test ! -z ${GCLOUD_PROJECT_ID:-};
+          then
+            echo "[i] GCLOUD_PROJECT_ID project set to ${GCLOUD_PROJECT_ID}.";
+          else
+            echo "[!] GCLOUD_PROJECT_ID environment variable must be set.";
+            exit 1;
+          fi
+        displayName: Check Google Cloud SDK project
         env:
           GCLOUD_PROJECT_ID: $(GCLOUD_PROJECT_ID)
 
-      - bash: |
-          gcloud deployment-manager deployments --project ${GCLOUD_PROJECT_ID} list
+      - script: gcloud projects get-iam-policy $(GCLOUD_PROJECT_ID) \
+          --flatten="bindings[].members" \
+          --format='table(bindings.role)' \
+          --filter="bindings.members:$(gcloud config get-value account)"
+        displayName: List Google Cloud SDK service account roles
         env:
           GCLOUD_PROJECT_ID: $(GCLOUD_PROJECT_ID)
 
-  - job: InfraDiff
-    displayName: "Diff infra things"
-    container: gitopsci
+- stage: Infrastructure
+  displayName: Infrastructure deploy
+  jobs:
+
+  - job: InfrastructureDiff
+    displayName: "Preview infrastructure changes"
+    container: gcloud
     dependsOn:
-      - ProviderConfig
+      - GoogleCloudEnvCheck
     steps:
 
-      - script: printenv
-
-      - bash: |
-          test ! -z ${GCLOUD_SERVICE_ACCOUNT:-} \
-            || { echo "[!] GCLOUD_SERVICE_ACCOUNT environment variable must be set."; exit 1; } \
-            && {
-              gcloud auth activate-service-account \
-                --key-file <(echo ${GCLOUD_SERVICE_ACCOUNT} | base64 -d) \
-              || { echo "[!] Unable to activate the service account."; exit 1; } \
-              && echo  [i] "Service account set to $(gcloud config get-value account)."
-            }
+      - script: >
+          gcloud auth activate-service-account
+          --key-file <(echo ${GCLOUD_SERVICE_ACCOUNT} | base64 -d)
         displayName: Activate Google Cloud SDK service account
         env:
           GCLOUD_SERVICE_ACCOUNT: $(GCLOUD_SERVICE_ACCOUNT)
 
       - bash: |
-          gcloud deployment-manager deployments --project ${GCLOUD_PROJECT_ID} list
+          while read manifest;
+          do
+            name=$(sed 's#.*/\([a-z]\+\)/\(.*\).yaml$#\1-\2#' <<< ${manifest});
+            test -z ${PREFIX} || name=${PREFIX}-${name};
+            echo "Preview $name $manifest";
+          done < <(find infra/${PROVIDER}/deployments/${ENVIRONMENT} -name '*yaml');
         env:
           GCLOUD_PROJECT_ID: $(GCLOUD_PROJECT_ID)
 
-      - script: kubectl version --client=true
-
+      - bash: |
+          while read manifest;
+          do
+            name=$(sed 's#.*/\([a-z]\+\)/\(.*\).yaml$#\1-\2#' <<< ${manifest});
+            test -z ${PREFIX} || name=${PREFIX}-${name};
+            echo "Update $name $manifest";
+          done < <(find infra/${PROVIDER}/deployments/${ENVIRONMENT} -name '*yaml');
+        env:
+          GCLOUD_PROJECT_ID: $(GCLOUD_PROJECT_ID)
 
 - stage: Storage
+  displayName: Storage deploy
   jobs:
-  - job: DEP
-    displayName: "Al igual y funciona"
-    container: gitopsci
-    steps:
-      - script: printenv
 
-      - bash: |
-          test ! -z ${GCLOUD_SERVICE_ACCOUNT:-} \
-            || { echo "[!] GCLOUD_SERVICE_ACCOUNT environment variable must be set."; exit 1; } \
-            && {
-              gcloud auth activate-service-account \
-                --key-file <(echo ${GCLOUD_SERVICE_ACCOUNT} | base64 -d) \
-              || { echo "[!] Unable to activate the service account."; exit 1; } \
-              && echo  [i] "Service account set to $(gcloud config get-value account)."
-            }
+  - job: CheckBuckets
+    displayName: "Check bucket existence"
+    container: gcloud
+    steps:
+
+      - script: >
+          gcloud auth activate-service-account
+            --key-file <(echo ${GCLOUD_SERVICE_ACCOUNT} | base64 -d)
         displayName: Activate Google Cloud SDK service account
         env:
           GCLOUD_SERVICE_ACCOUNT: $(GCLOUD_SERVICE_ACCOUNT)
 
-      - bash: |
-          gcloud deployment-manager deployments --project ${GCLOUD_PROJECT_ID} list
+      - script: >
+          gcloud deployment-manager deployments
+            --project ${GCLOUD_PROJECT_ID} list
         env:
           GCLOUD_PROJECT_ID: $(GCLOUD_PROJECT_ID)
 
-      - script: kubectl version --client=true
+      - bash: |
+          while read bucket;
+          do
+            name=$(sed 's#.*/\([a-z]\+\)/\(.*\)$#\1-\2#' <<< ${bucket})
+            test -z ${PREFIX} || name=${PREFIX}-${name}
+            echo gsutil ls gs://$name $bucket
+          done < <(find storage/${ENVIRONMENT} -maxdepth 1 -mindepth 1 -type d)
+
+- stage: Kubernetes
+  displayName: Kubernetes deploy
+  jobs:
+
+  - job: Check k8s environment
+    displayName: "Check bucket existence"
+    container: gcloud
+    steps:
+
+      - script: >
+          gcloud auth activate-service-account
+            --key-file <(echo ${GCLOUD_SERVICE_ACCOUNT} | base64 -d)
+        displayName: Activate Google Cloud SDK service account
+        env:
+          GCLOUD_SERVICE_ACCOUNT: $(GCLOUD_SERVICE_ACCOUNT)
+
+      - script: >
+          K8S_CLUSTER_LOCATION=$(
+            sed -n 's/^cluster-location\s\+\(.*\)/\1/p'
+            <(gcloud --project ${GCLOUD_PROJECT_ID} \
+              deployment-manager deployments describe ${K8S_CLUSTER});
+        displayName: Get GKE cluster location
+        env:
+          GCLOUD_PROJECT_ID: $(GCLOUD_PROJECT_ID)
+
+      - bash: |
+          if egrep -q '[a-z]+-[a-z]+[0-9]-[a-z]' <<<${K8S_CLUSTER_LOCATION};
+          then
+            GCLOUD_CLUSTER_LOCATION_FLAG="--region ${K8S_CLUSTER_LOCATION}";
+          else
+            GCLOUD_CLUSTER_LOCATION_FLAG="--zone ${K8S_CLUSTER_LOCATION}";
+          fi
+        displayName: Set GKE cluster location flag
+
+      - bash:
+          if gcloud --project ${GCLOUD_PROJECT_ID} \
+              container clusters get-credentials ${K8S_CLUSTER} \
+              ${GCLOUD_CLUSTER_LOCATION_FLAG};
+          then
+            echo "[i] kubectl cluster set to ${K8S_CLUSTER}.";
+          else
+            echo "[!] unable to retrieve cluster credentials.";
+          fi
+        displayName: Retrieve GKE cluster credentials
+
+      - script: >
+          echo kubectl get pods
